spring.application.name=product-app

spring.datasource.url=jdbc:postgresql://localhost:5432/oop_lab
spring.datasource.username=postgres
spring.datasource.password=MaineVet_0725

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true