spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=84ea14ec59e1

spring.devtools.restart.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true