# Change this to your actual database name (e.g., postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
# Use the password you set during PostgreSQL installation
spring.datasource.password=kenneth

# This tells Hibernate to talk "Postgres language"
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# This creates/updates your tables automatically based on your Java classes
spring.jpa.hibernate.ddl-auto=update