spring.application.name=app-demo

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/app_demo
spring.datasource.username=postgres
spring.datasource.password=MaineVet_0725

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect