spring.application.name=demo

# H2 (commented out, do not delete)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.h2.console.enabled=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

