name: Build Java Files

on:
  push:
    branches: [ main, develop-* ]
  pull_request:
    branches: [ main, develop-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Detect and Build Project
        run: |
          if [ -f "pom.xml" ]; then
            echo "Maven project detected"
            mvn clean install -DskipTests
          
          else
            echo "Plain Java project detected"
            mkdir -p bin
            find . -name "*.java" > sources.txt
            javac -d bin -cp bin @sources.txt
          fi
